### ISSUE TITLE
JS enhanced header links

### ISSUE THREAD

**Issue by swantzter** [Libera-Chat/libera-chat.github.io#21]
essentially:

```js
document.querySelectorAll('main :is(h2,h3,h4,h5,h6)')
  .forEach(el => {
    el.innerHTML = `<a href="#${el.id}">${el.innerHTML}</a>`
})
```

and

```css
main :is(h2, h3, h4, h5, h6) a {
  text-decoration: none;
}

main :is(h2, h3, h4, h5, h6) a:hover::before {
  content: '#';
  position: absolute;
  left: 0;
}
```
