### ISSUE TITLE
Add GitHub action to run markdownlint

### ISSUE THREAD

**Issue by swantzter** [Libera-Chat/libera-chat.github.io#69]
I have this `.markdownlint.yml` and action laying around from other projects with what I usually go for, but I think it might need to be adapted slightly to fit Libera Chat

```yml
default: true

# MD003/heading-style/header-style - Heading style
MD003:
  # Heading style
  style: atx

# MD004/ul-style - Unordered list style
MD004:
  # List style
  style: dash

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  # Spaces for line break
  br_spaces: 0
  # Allow spaces for empty lines in list items
  list_item_empty_lines: false
  # Include unnecessary breaks
  strict: false

# MD013/line-length - Line length
MD013: 78

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements:
    - sup
    - sub
    - br

# MD035/hr-style - Horizontal rule style
MD035:
  # Horizontal rule style
  style: "---"

# MD042/no-empty-links - No empty links
# This is checked by check-md instead
MD042: false

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  # List of proper names
  names:
    - Libera.Chat
    - Libera Chat
  # Include code blocks
  code_blocks: false

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: fenced

# MD048/code-fence-style - Code fence style
MD048:
  # Code fence syle
  style: backtick
```

`.github/workflows/lint.yml`
```yml
name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    name: Check markdown for style issues
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npx markdownlint '**/*.md' --ignore node_modules
      - uses: xt0rted/markdownlint-problem-matcher@v1
        if: success() || failure()
        with:
          action: remove

  check-md:
    name: Check that all links exist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i check-md

      - run: echo "::add-matcher::.github/workflow-support/check-md-matcher.json"
      - run: 
      - run: echo "::remove-matcher owner=check-md::"
        if: success() || failure()
```

`.github/workflow-support/check-md.js` 
```js
const { check } = require('check-md')
const path = require('path')

check({
  pattern: '**/*.md',
  ignore: ['**/node_modules'],
  exitLevel: 'error',
  root: ['./', './content'],
  defaultIndex: ['README.md', 'index.md'],
  slugify: compose(deeplyParseHeaders, slugify),
  cwd: process.cwd()
}).then(result => {
  let failed = false
  for (const { type, list } of Object.values(result)) {
    for (const match of list) {
      failed = true
      const relativePath = path.relative(process.cwd(), match.fileUrl)
      console.error(`${relativePath}:${match.line}:${match.col}:${type === 'warn' ? 'warning' : type}:${match.errMsg}`)
    }
  }
  process.exit(failed ? 1 : 0)
})
```

`.github/workflow-support/check-md-matcher.json`
```json
{
  "problemMatcher": [
    {
      "owner": "check-md",
      "pattern": [
        {
          "regexp": "^(.+):(\\d+):(\\d+):(error|warning):(.+)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      ]
    }
  ]
}
```
